title: Ahamad Kansoun
description: Ingénieur en électronique et systèmes embarqués | Microcontrôleurs • Conception électronique • PCB • FreeRTOS • IoT
theme: jekyll-theme-leap-day

author:
  name: Ahamad Kansoun
  email: ahmadk162@gmail.com

github_username: ahmadk162
linkedin_username: ahamad-kansoun


markdown: kramdown

