title: Ahamad Kansoun
description: Control Systems & Energy Systems Engineer | Digital Twin | PVT Systems
theme: minima

author:
  name: Ahamad Kansoun
  email: ahamad.kansoun@u-picardie.fr

github_username: your_github_username
linkedin_username: your_linkedin_username

markdown: kramdown

