title: Ahamad Kansoun
description: Ingénieur en électronique et systèmes embarqués
Microcontrôleurs • Conception électronique • PCB • FreeRTOS • IoT
theme: minima

author:
  name: Ahamad Kansoun
  email: ahmadk162@gmail.com

github_ahmadk162: ahmadk162
linkedin_username: your_linkedin_username

markdown: kramdown

